//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneTakipSistemi.HastaneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class doktorlar
    {
        public int dr_id { get; set; }
        public string dr_ad { get; set; }
        public string dr_soyad { get; set; }
        public string email { get; set; }
        public string dr_dogum { get; set; }
        public string dr_tc { get; set; }
        public string dr_alan { get; set; }
        public string dr_il { get; set; }
        public string dr_ilçe { get; set; }
        public string dr_tel { get; set; }
        public string dr_cins { get; set; }
        public string dr_sifre { get; set; }
        public Nullable<int> dr_klinik { get; set; }
    }
}
