//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneTakipSistemi.HastaneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eczacilar
    {
        public int eczaci_id { get; set; }
        public string eczaci_ad { get; set; }
        public string eczaci_soyad { get; set; }
        public string email { get; set; }
        public string eczaci_dogum { get; set; }
        public string eczaci_tc { get; set; }
        public string eczaci_il { get; set; }
        public string eczaci_ilçe { get; set; }
        public string eczaci_tel { get; set; }
        public string eczaci_cins { get; set; }
        public string eczaci_sifre { get; set; }
    }
}
