//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneTakipSistemi.HastaneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastalar
    {
        public int hasta_id { get; set; }
        public string hasta_tc { get; set; }
        public string hasta_ad { get; set; }
        public string hasta_soyad { get; set; }
        public string hasta_dogum { get; set; }
        public string hasta_dyeri { get; set; }
        public string hasta_adres { get; set; }
        public string hasta_il { get; set; }
        public string hasta_ilce { get; set; }
        public string hasta_cins { get; set; }
        public string hasta_tel { get; set; }
        public string hasta_anne { get; set; }
        public string hasta_baba { get; set; }
        public string hasta_sgk { get; set; }
        public string hasta_mail { get; set; }
        public string hasta_sifre { get; set; }
        public string hasta_oda { get; set; }
        public string hasta_yatak { get; set; }
    }
}
