//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneTakipSistemi.HastaneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hemsireler
    {
        public int hemsire_id { get; set; }
        public string hemsire_ad { get; set; }
        public string hemsire_soyad { get; set; }
        public string email { get; set; }
        public string hemsire_dogum { get; set; }
        public string hemsire_tc { get; set; }
        public string hemsire_alan { get; set; }
        public string hemsire_il { get; set; }
        public string hemsire_ilçe { get; set; }
        public string hemsire_tel { get; set; }
        public string hemsire_cins { get; set; }
        public string hemsire_sifre { get; set; }
    }
}
