//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneTakipSistemi.HastaneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevular
    {
        public int randevu_id { get; set; }
        public string randevu_tarihi { get; set; }
        public string randevu_saati { get; set; }
        public string dr_id { get; set; }
        public string hasta_id { get; set; }
        public string klinik_id { get; set; }
    }
}
